language: python
env:
    - TOXENV=py27
install:
    - pip install tox
script:
    - tox
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sudo apt install -y python-numpy python-scipy
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - ./install_paintor.sh
